spring:
  docker:
    compose:
      file: './consumer/redis-compose.yml'
      enabled: true
      lifecycle-management: start_and_stop
      stop:
        command: down
        timeout: 10
  cloud:
    function:
      definition: generateReport|log
    stream:
      function:
        bindings:
          generateReportlog-in-0: input
      bindings:
        input:
          destination: coin-data-upbit.json
          group: log
server:
  port: 8087
