spring:
  docker:
    compose:
      file: './message-server/kafka-compose.yml'
      enabled: true
      lifecycle-management: start_and_stop
      stop:
        command: down
        timeout: 10
  cloud:
    function:
      definition: transformExrateData
    stream:
      function:
        bindings:
          transformExrateData-in-0: input
          transformExrateData-out-0: output
      bindings:
        input:
          destination: raw-coin-data
          content-type: text/plain
          group: coin
        output:
          destination: coin-data
          content-type: application/json


server:
  port: 9999
