spring:
  config:
    import:
      - secrets-manager.yml
  cloud:
    function:
      definition: createExrateDataSupplier
    stream:
      poller:
        fixed-delay: 20000
      function:
        bindings:
          createExrateDataSupplier-out-0: output
      bindings:
        output:
          destination: raw-exrate-data
          content-type: text/plain

coin:
  upbit:
    api:
      base-url: https://api.upbit.com
      market-code-url: /v1/market/all
      candles-minutes-url: /v1/candles/minutes/1

server:
  port: 8086
