spring:
  config:
    import:
      - secrets-manager.yml
  cloud:
    function:
      definition: createExrateDataSupplier
    stream:
      poller:
        fixed-delay: 20000
      function:
        bindings:
          createExrateDataSupplier-out-0: output
      bindings:
        output:
          destination: usgs-exrate-data
          content-type: application/json
          binder: kafka

exrate:
  api:
    base-url: https://www.koreaexim.go.kr
    exrate-url: /site/program/financial/exchangeJSON
    auth-key: ${exrate.krexim.authKey}




server:
  port: 8086
